# Generated by Django 3.2.25 on 2025-06-15 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del club')),
                ('fecha_fundacion', models.DateField(verbose_name='Fecha de fundación')),
                ('descripcion', models.TextField(help_text='Uno o dos párrafos', verbose_name='Descripción breve')),
                ('escudo_url', models.URLField(verbose_name='URL del escudo')),
                ('estadio_url', models.URLField(verbose_name='URL de la imagen del estadio')),
                ('logro_destacado', models.TextField(verbose_name='Logro más importante del club')),
                ('descripcion_estadio', models.TextField(verbose_name='Descripción del estadio')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='publicacion',
        ),
    ]
